stages:
  ingestion:
    cmd: python src/document_iq_dl/components/data_ingestion.py
    deps:
      - data/raw/FUNSD
      - src/document_iq_dl/components/data_ingestion.py
    outs:
      - data/interim/funsd_blocks.json
  validation:
    cmd: python src/document_iq_dl/components/data_validation.py
    deps:
      - data/interim/funsd_blocks.json
      - src/document_iq_dl/components/data_validation.py
    outs:
      - artifacts/validation_report.json
