stages:
  ingestion:
    cmd: python src/document_iq_dl/components/data_ingestion.py
    deps:
      - data/raw/FUNSD
      - src/document_iq_dl/components/data_ingestion.py
    outs:
      - data/interim/funsd_blocks.json
