stages:

  yolo_data_ingestion:
    cmd: python src/document_iq_dl/components/yolo_data_ingestion.py
    deps:
      - data/raw/FUNSD
      - src/document_iq_dl/datasets/funsd_to_yolo.py
      - src/document_iq_dl/components/yolo_data_ingestion.py
    outs:
      - data/yolo

  yolo_data_validation:
    cmd: python src/document_iq_dl/components/yolo_data_validation.py
    deps:
      - data/yolo
      - src/document_iq_dl/components/yolo_data_validation.py
    outs:
      - artifacts/dataset

  yolo_training:
    cmd: python src/document_iq_dl/components/yolo_model_trainer.py
    deps:
      - data/yolo
      - configs/yolo_training.yaml
      - src/document_iq_dl/components/yolo_model_trainer.py
    outs:
      - artifacts/yolo_model

  yolo_evaluation:
    cmd: python src/document_iq_dl/components/yolo_model_evaluation.py
    deps:
      - artifacts/yolo_model
      - src/document_iq_dl/components/yolo_model_evaluation.py