stages:
  ingestion:
    cmd: python src/document_iq_dl/components/data_ingestion.py
    deps:
      - data/raw/FUNSD
      - src/document_iq_dl/components/data_ingestion.py
    outs:
      - data/interim/funsd_blocks.json
  validation:
    cmd: python src/document_iq_dl/components/data_validation.py
    deps:
      - data/interim/funsd_blocks.json
      - src/document_iq_dl/components/data_validation.py
    outs:
      - artifacts/validation_report.json
  transformation:
    cmd: python src/document_iq_dl/components/data_transformation.py
    deps:
      - data/interim/funsd_blocks.json
      - src/document_iq_dl/components/data_transformation.py
    outs:
      - data/processed
  training:
    cmd: python src/document_iq_dl/components/model_trainer.py
    deps:
      - data/processed
      - configs/training.yaml
      - src/document_iq_dl/components/model_trainer.py
      - src/document_iq_dl/models/layout_classifier.py
      - src/document_iq_dl/datasets/funsd_dataset.py
    outs:
      - artifacts/model
  evaluation:
    cmd: python src/document_iq_dl/components/model_evaluation.py
    deps:
      - artifacts/model
      - data/processed
      - configs/training.yaml
      - src/document_iq_dl/components/model_evaluation.py
    outs:
      - artifacts/evaluation
