version: "3.9"

services:
# ---------------------------------------------------------
# Kafka and Zookeeper
# ---------------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"   # 👈 LOCAL clients use this
      - "9092:9092"     # 👈 Docker clients use this
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

# ---------------------------------------------------------
# Databases
# ---------------------------------------------------------

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-server

    ports:
      - "3308:8000"

    volumes:
      # Persistent storage
      - chroma_data:/chroma/chroma

    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma

    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "3309:27017"
    volumes:
      - mongo_data:/data/db
# ----------------------------------------
# Logging Stack
# ----------------------------------------

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./infra/logging/loki-config.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/logging/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./infra/logging/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"   # Tempo HTTP
      - "4317:4317"   # OTLP gRPC
# ---------------------------------------------------------
# Platform Microservices
# ---------------------------------------------------------

  aggregator:
    build:
      context: .
      dockerfile: components/aggregator/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      service: aggregator
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_ACCOUNT_COMPONENT_URL: http://account-component:8001
      DOCUMENT_IQ_APPLICATION_COMPONENT_URL: http://application-component:8002
    command: python -m document_iq_platform_aggregator.main

  dlq-tooling:
    build:
      context: .
      dockerfile: ops/dlq-tooling/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      service: dlq-toolin
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    command: python -m document_iq_dlq_tooling.monitor

  ui-bff:
    build:
      context: .
      dockerfile: gateways/ui-bff/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    labels:
      service: ui-bff
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_ACCOUNT_COMPONENT_URL: http://account-component:8001
      DOCUMENT_IQ_APPLICATION_COMPONENT_URL: http://application-component:8002
      DOCUMENT_IQ_UI_PORTAL_URL : http://localhost:3000

  ingestion-worker:
    build:
      context: .
      dockerfile: components/ingestion-worker/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      service: ingestion-worker
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    volumes:
      - ingestion-data:/srv/data
    restart: unless-stopped

  classification-engine:
    build:
      context: .
      dockerfile: components/classification-engine/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      service: classififcation-engine
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    env_file:
    - .env

    restart: unless-stopped

  layout-engine:
    build:
      context: .
      dockerfile: components/layout-engine/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      service: layout-engine
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_ENV : prod
    env_file:
      - .env
    volumes:
      - ingestion-data:/srv/data
    restart: unless-stopped

  ocr-adapter:
    build:
      context: .
      dockerfile: components/ocr-adapter/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    labels:
      service: ocr-adapter
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    env_file:
      - .env
    restart: unless-stopped

  rag-engine:
    build:
      context: .
      dockerfile: components/rag-engine/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      chromadb:
        condition: service_started
    labels:
      service: rag-engine
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_RAG_LLM_PROVIDER : groq
      DOCUMENT_IQ_ACCOUNT_COMPONENT_URL: http://account-component:8001
      DOCUMENT_IQ_APPLICATION_COMPONENT_URL: http://application-component:8002
      DOCUMENT_IQ_MONGO_URI : "mongodb://mongo:3309"
    env_file:
      - .env
    restart: unless-stopped

  account-component:
    build:
      context: .
      dockerfile: components/account-component/Dockerfile
    labels:
      service: account-component
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_MONGO_URI : "mongodb://mongo:3309"
      DOCUMENT_IQ_DATABASE_URL : mysql+pymysql://account_user:account_pass123@mysql:3306/document_iq_account_db
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - kafka

  application-component:
    build:
      context: .
      dockerfile: components/application-component/Dockerfile
    labels:
      service: application-component
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_DATABASE_URL : mysql+pymysql://application_user:application_pass123@mysql:3307/document_iq_application_db
      DOCUMENT_IQ_RAG_ENGINE_URL : "http://rag-engine:8003"
      DOCUMENT_IQ_MONGO_URI : "mongodb://mongo:3309"
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - mysql
      - mongo
      - kafka

  ui-portal:
    build:
      context: .
      dockerfile: ui-portal/document-iq-platform-ui/Dockerfile
    ports:
      - "3000:80"
    labels:
      service: ui-portal
    depends_on:
      - ui-bff

volumes:
  ingestion-data:
  mysql_data:
  chroma_data:
  mongo_data: